version: '2'
services:
  web:
    image: wxti/apache-php7
    volumes:
      - .:/var/www/html
    ports:
      - 80:80
    working_dir: /var/www/html

  mysql:
      image: mysql:5.7
      ports:
      - 3306:3306
      environment:
      - MYSQL_DATABASE=crudnodejs
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
      volumes:
      - ./database:/docker-entrypoint-initdb.d/

  phpmyadmin:
      image: phpmyadmin/phpmyadmin
      ports:
      - 82:80
      environment:
      - PMA_HOST=mysql
      - PMA_USER=root
      - TESTSUITE_PASSWORD=
      links:
      - mysql

